name = "hotbot"
main = "dist/index.js"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2025-09-15"


# Sensitive variables should be set as secrets (not in this file)
# Run: wrangler secret put CLERK_SECRET_KEY
# Run: wrangler secret put DATABASE_URL
# Run: wrangler secret put GITHUB_CLIENT_SECRET
# etc.

[site]
bucket = "dist"

[build]
command = "npm run build"
watch_dir = "src"

[observability.logs]
enabled = true